spring:
  datasource:
    url: jdbc:h2:mem:test_mem
    username: sa
    password: sa

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: true
  data:
    rest:
      base-path: /v1/resources
  flyway:
    enabled: true

server:
  error:
    include-message: always
